DROP TABLE IF EXISTS post;

CREATE TABLE post (
    no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(50) DEFAULT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    writer VARCHAR(100) NOT NULL,
    content TEXT,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
